apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  
spec:
  #Type could be: ClusterIP,NodePort,LoadBalancer,ExternalName
  type: NodePort
  ports:
      #Port on the pod
    - targetPort: 80
      #Port is on the target service
      port: 80
      #
      nodePort: 30008
  selector:
   #From the label: value of the pods
   app: myapp
   type: front-end

