apiVersion: v1
kind: Pod
metadata:
  name: postgres-app
  labels:
    name: postgres-app
    app: voting-app

spec:
  containers:
  - name: postgres-pod
    image: postgres:9.4
    ports:
    - containerPort: 5432


