apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app

spec:
  ports:
  - port: 6397
    targetPort: 6379
  selector:
    name: redis-app
    app: voting-app

